---
Name: mappable
After: 'framework/*','cms/*'
---

DataObject:
  extensions:
    -  MappableData

DataList:
  extensions:
    -  MappableDataObjectSet

ArrayList:
  extensions:
    -  MappableDataObjectSet


# allow geographical format files to be uploaded
File:
  $allowed_extensions: ['gpx', 'kml']

